#!/bin/bash

source .env
if ! [[ $DEPLOY_HOST && $DEPLOY_PATH ]]; then
  echo DEPLOY_HOST and DEPLOY_PATH must be defined
  exit 1
fi

target=$DEPLOY_HOST:$DEPLOY_PATH
echo "Deploying assets and html to production... $target"
rsync -avzP public/ $target

ssh $DEPLOY_HOST "\
  cd $DEPLOY_PATH; \
  mv exported.html index.html; \
  mv exported.html.gz index.html.gz"
